name:                yhseq
version:             0.2.1.0
github:              "Hexirp/yhseq"
license:             Apache-2.0
author:              "Hexirp"
maintainer:          "https://github.com/Hexirp/yhseq"
copyright:           "(C) Hexirp 2019"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Calculation of Y-sequence Hexirp edition
category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Hexirp/yhseq#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  yhseq-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yhseq

tests:
  yhseq-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yhseq
    - hspec >= 2.5.0 && < 3.0.0
    - hspec-discover >= 2.5.0 && < 3.0.0
